
-- SCRIPT DE ESTRUCTURA DE BASE DE DATOS DE LABORATORIO

CREATE TABLE ROLES (
	ID_ROL INT IDENTITY PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE USUARIOS (
	ID_USUARIO INT IDENTITY PRIMARY KEY,
	NOMBRE_COMPLETO VARCHAR(200) NOT NULL,
	CORREO VARCHAR(320) NOT NULL UNIQUE,
	CONTRASENA VARCHAR(255) NOT NULL,
	ID_ROL INT NOT NULL REFERENCES ROLES(ID_ROL),
	ACTIVO BIT NOT NULL
);

CREATE TABLE ACCIONES_RESERVA (
	ID_ACCION INT IDENTITY PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE ESTADOS_RESERVA (
	ID_ESTADO INT IDENTITY PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE RESERVAS (
	ID_RESERVA VARCHAR(16) PRIMARY KEY,
	DESCRIPCION VARCHAR(100) NOT NULL,
	FECHA DATE NOT NULL,
	HORA_INICIO TIME NOT NULL,
	HORA_FIN TIME NOT NULL,
	ID_ESTADO INT NOT NULL REFERENCES ESTADOS_RESERVA(ID_ESTADO)
);

CREATE TABLE HISTORIAL_RESERVAS (
	ID_HISTORIAL VARCHAR(16) PRIMARY KEY,
	ID_RESERVA VARCHAR(16) NOT NULL REFERENCES RESERVAS(ID_RESERVA),
	FECHA_MODIFICACION DATETIME NOT NULL,
	ID_ACCION INT NOT NULL REFERENCES ACCIONES_RESERVA(ID_ACCION),
	ID_USUARIO INT NOT NULL REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE TIPOS_MOVIMIENTOS (
	ID_TIPO_MOVIMIENTO INT IDENTITY PRIMARY KEY,
	NOMBRE VARCHAR(20) NOT NULL UNIQUE,
	FACTOR INT NOT NULL
);

CREATE TABLE MARCAS (
	ID_MARCA INT IDENTITY PRIMARY KEY,
	NOMBRE VARCHAR(50) UNIQUE
);

CREATE TABLE CLASIFICACION_REACTIVOS (
	ID_CLASIFICACION INT IDENTITY PRIMARY KEY,
	NOMBRE VARCHAR(50) UNIQUE
);

CREATE TABLE REACTIVOS (
	ID_REACTIVO VARCHAR(17) PRIMARY KEY,
	NOMBRE VARCHAR(100) NOT NULL ,
	ID_MARCA INT REFERENCES MARCAS(ID_MARCA),
	PESO_NETO FLOAT NOT NULL,
	PESO_FRASCO FLOAT NOT NULL,
	ID_CLASIFICACION INT REFERENCES CLASIFICACION_REACTIVOS(ID_CLASIFICACION),
	UBICACION VARCHAR(100),
	OBSERVACIONES VARCHAR(100),
	COLOR VARCHAR(50)
);

CREATE TABLE MOVIMIENTOS_REACTIVOS (
	ID_MOVIMIENTO VARCHAR(17) PRIMARY KEY,
	ID_REACTIVO VARCHAR(17) NOT NULL REFERENCES REACTIVOS(ID_REACTIVO),
	CANTIDAD FLOAT NOT NULL,
	FECHA DATETIME,
	ID_TIPO_MOVIMIENTO INT NOT NULL REFERENCES TIPOS_MOVIMIENTOS(ID_TIPO_MOVIMIENTO)
);

CREATE TABLE CRISTALERIA (
	ID_CRISTALERIA VARCHAR(16) PRIMARY KEY,
	DESCRIPCION VARCHAR(100) NOT NULL,
	CANTIDAD INT NOT NULL,
	CANT_BUEN_ESTADO INT NOT NULL,
	CANT_RAJADO_FUNCIONAL INT NOT NULL,
	CANT_DANADO INT NOT NULL,
	OBSERVACIONES VARCHAR(100)
);

CREATE TABLE MOVIMIENTOS_CRISTALERIA (
	ID_MOVIMIENTO VARCHAR(17) PRIMARY KEY,
	ID_CRISTALERIA VARCHAR(16) NOT NULL REFERENCES CRISTALERIA(ID_CRISTALERIA),
	CANTIDAD INT NOT NULL,
	FECHA DATETIME NOT NULL,
	ID_TIPO_MOVIMIENTO INT NOT NULL REFERENCES TIPOS_MOVIMIENTOS(ID_TIPO_MOVIMIENTO)
);

GO